# Generated by Django 4.0.2 on 2022-02-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=500)),
                ('photos', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('facebook_link', models.URLField(max_length=500)),
                ('twitter_link', models.URLField(max_length=500)),
                ('google_plus_link', models.URLField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
