# Generated by Django 4.0.2 on 2022-02-21 14:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_door'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='door',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=9),
        ),
    ]
